apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-app-dep
  labels:
    app: scale-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-app

  template:
    metadata:
      labels:
        app: scale-app
    spec:
      containers:
        - name: scale-app
          image: shestera/scaletestapp
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "20Mi"
            requests:
              memory: "20Mi"